# Generated by Django 3.1.3 on 2020-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20201125_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
