# Generated by Django 3.1.3 on 2020-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9),
        ),
    ]
